cmake_minimum_required(VERSION 3.16)
project(browser_network C)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O2")
add_compile_definitions(MBEDTLS_USER_CONFIG_FILE="tls-config.h")
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
add_subdirectory(${MBEDTLS_DIR} mbedtls)
include(${LWIP_DIR}/src/Filelists.cmake)
add_executable(browser-net network.c ${lwipcore_SRCS} ${lwipcore4_SRCS} ${LWIP_DIR}/src/netif/ethernet.c)
target_include_directories(browser-net PRIVATE ${LWIP_DIR}/src/include ${CMAKE_CURRENT_BINARY_DIR})
target_link_libraries(browser-net PRIVATE mbedtls mbedx509 mbedcrypto)
set_target_properties(browser-net PROPERTIES SUFFIX ".mjs")
target_link_options(browser-net PRIVATE -O2 --no-entry -sMODULARIZE=1 -sEXPORT_ES6=1 -sENVIRONMENT=web,worker,node -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=16777216 -sMAXIMUM_MEMORY=67108864 -sSTACK_SIZE=262144 -sFILESYSTEM=0 -sEXPORTED_RUNTIME_METHODS=HEAPU8 "-sEXPORTED_FUNCTIONS=['_net_init','_net_input','_net_tick','_net_write','_net_end','_net_abort','_malloc','_free']")
